[package]
name = "bow"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "56.0.0"
clap = { version = "4.5.45", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
uuid = { version = "1.18.0", features = ["v4"] }
